mutation RejectChildDeletion(
  $calculationId: UUID! = "uuid.NewSHA1(uuid('33333333-3333-3333-3333-333333333333'), bytes('YYYY'))"
    @cel
) {
  deleteCalculation(id: $calculationId) {
    calculationId
  }
}
