mutation RejectChildAttachment(
  $calculationId: UUID! = "uuid.NewSHA1(uuid('77777777-7777-7777-7777-777777777777'), bytes('YYYY'))"
    @cel
) {
  attachCalculation(
    input: {
      accountId: "e5703d6c-d484-11f0-bcff-069b540ea27e"
      calculationId: $calculationId
      journalId: "11111111-1111-1111-1111-111111111111"
    }
  ) {
    calculationId
    journalId
  }
}
